---
title: "R Notebook"
output: html_notebook
---
 

```{r}
table <-read.table(file="cc3N.txt",header=TRUE)
```

```{r}
assignation <-table$Assignation
station<- c("A2", "A3", "B2", "A5", "M2", "A8", "M7", "N6", "C3", "D2", "E2", "F3")
```

```{r}
TEST <-c(table$A2, table$A3, table$B2,table$A5, table$M2, table$A8, table$M7, table$N6, table$C3, table$D2, table$E2, table$F3)
```

```{r}
station
```


```{r}
data <- data.frame(
  name=table$Assignation ,  
  value= c(table$A2, table$A3, table$B2,table$A5, table$M2, table$A8, table$M7, table$N6, table$C3, table$D2, table$E2, table$F3)
  )
ggplot(data, aes(x=name, y=value)) + 
  geom_bar(stat = "identity")
```
```{r}
data <- data.frame(
  name=c(table$A2, table$A3, table$B2,table$A5, table$M2, table$A8, table$M7, table$N6, table$C3, table$D2, table$E2, table$F3),  
  value= table$Assignation
  )
ggplot(data, aes(x=name, y=value)) + 
  geom_bar(stat = "identity")
```

```{r}
df <- structure(list(Sample = structure(1:12, .Label = c("A2", "A3", "B2", "A5", "M2", "A8", "M7", "N6", "C3", "D2", "E2", "F3"), class = "factor"), Acidobacteria = c(9.3,5.0,5.5,7.4,6.1,3.8,8.6,3.9,7.0,7.1,7.9,8.6), Actinobacteria = c(3.7,4.1,	2.0,2.0,2.3,0.7,2.1,1.4,1.1,0.8,0.8,0.7), Alphaproteobacteria = c(4.8,4.6,2.5,4.3,5.6,3.4,6.4,4.7,3.5,2.8,3.7,3.8), Bacteroidetes = c(10.3,17.0,8.6,18.2,17.6,0.9,15.4,37.6,12.6,10.4), Betaproteobacteria = c(0.2,0.1,0.1,0.3,0.1,0.1,1.0,0.4,0.3,0.4,0.3,0.3), Candidate_division_OP8 = c(0.5,0.2,1.4,0.4,0.2,9.2,0.2,0.1,0.2,0.4,0.4,1.0), Candidate_division_WS3 = c(2.7,2.4,2.2,3.1,2.4,1.4,2.0,1.2,2.6,3.1,2.6,2.2),Chlorobi = c(0.5,0.3,0.4,0.3,0.3,0.3,0.3,0.1,0.6,1.1,0.7,0.4)  ,Chloroflexi = c(6.1,3.7,6.4,3.0,3.3,11.9,2.6,1.5,3.9,4.5,3.7,5.1) ,
Cyanobacteria = c(0.7,1.3,0.7,0.9,1.3,0.1,0.5,0.5,1.9,1.4,0.2,0.1) ,Deferribacteres = c(0.4,0.3,0.6,0.7,0.3,1.3,0.4,0.1,0.6,1.0,0.7,1.0),Deltaproteobacteria = c(21.7,22.0,31.2,18.4,21.8,25.0,18.1,18.1,28.2,27.8,37.9,34.0),Epsilonproteobacteria = c(0.2,0.4,0.2,0.5,0.1,0.1,0.1,0.1,0.3,0.3,0.4,0.1),Firmicutes = c(0.4, 1.2,0.7,3.3,0.1, 0.5, 0.1, 1.2,0.9,0.4, 0.1,0.1), Gemmatimonadetes = c(1.2, 0.9,1.1,1.6,1.0,0.9,2.2,1.0,1.8,1.7,2.5,1.8),Lentisphaerae = c(0.6,1.2,0.9,0.7,0.9,0.9,0.6,0.6,0.7,0.8,0.4,0.2),Nitrospirae = c(0.4,0.2,1.9,0.5,0.4,2.5,1.0,0.2,1.2,1.2,2.5,4.8),Planctomycetes = c(14.6,10.3,6.9,8.4,9.8,5.6,11.5,6.6,5.5,6.1,6.2,7.1),Spirochaetae = c(0.3,0.5,1.3,1.1,0.4,2.5,0.1,0.9,0.3,0.6,0.6,0.7),Unclassified = c(1.7,1.5,8.7,1.0,1.9,14.4,1.1,0.9,1.6,4.3,1.5,5.0),Other = c(1.2,1.4,1.4,1.9,0.8,1.8,1.6,1.0,1.0,1.0,1.1,1.1)),.Names = c("Station", "Acidobacteria", "Actinobacteria", 
"Alphaproteobacteria", "Bacteroidetes", "Betaproteobacteria","Candidate_division_OP8","Candidate_division_WS3","Chlorobi", "Chloroflexi", "Cyanobacteria","Deferribacteres","Deltaproteobacteria","Epsilonproteobacteria","Firmicutes","Gemmatimonadetes","Lentisphaerae","Nitrospirae","Planctomycetes","Spirochaetae","Unclassified", "Other"), class = "data.frame", row.names = c("1", "2", "3","4", "5", "6","7", "8", "9","10", "11", "12"))
```

```{r}
library(reshape2)
df_long <- melt(df, id.vars = "Station", variable.name = "Phyla")
```

```{r}
library(ggplot2)
ggplot(df_long, aes(x = Station, y = value, fill = Phyla)) + 
    geom_bar(stat = "identity")
```























